"""posts table with date time without host

Revision ID: 3829ddf4f302
Revises: 6d15bf3c77ed
Create Date: 2021-05-23 22:19:10.441174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3829ddf4f302'
down_revision = '6d15bf3c77ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_name'), 'post', ['name'], unique=True)
    op.drop_column('post', 'host')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('host', sa.VARCHAR(length=140), nullable=True))
    op.drop_index(op.f('ix_post_name'), table_name='post')
    # ### end Alembic commands ###
