"""regLink

Revision ID: ead53668ae98
Revises: 3829ddf4f302
Create Date: 2021-05-24 16:14:33.583652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead53668ae98'
down_revision = '3829ddf4f302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('regLink', sa.VARCHAR(length=20000), nullable=True))
    op.create_index(op.f('ix_post_regLink'), 'post', ['regLink'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_regLink'), table_name='post')
    op.drop_column('post', 'regLink')
    # ### end Alembic commands ###
